// VERSAVISUAL Image System
// Sourced from project productions, categorized by album & segment.

const LOCAL_IMAGE_FALLBACK = "/images/foto-a-producao-nao-falha.webp"

export function img(id: string, w = 1200, h?: number): string {
  if (!id) return ""
  if (id.startsWith("/") || id.startsWith("http") || id.startsWith("data:")) {
    return id
  }
  return LOCAL_IMAGE_FALLBACK
}

export function getImageAlt(
  src: string,
  contextTitle = "Produção audiovisual",
): string {
  if (!src) return "Produção audiovisual autoral VERSAVISUAL"
  const filename = src.split("/").pop() || ""
  const cleanName = decodeURIComponent(filename)
    .replace(/\.[^/.]+$/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\d+$/, "")
    .trim()
  if (cleanName && cleanName.length > 3) {
    return `${cleanName} — ${contextTitle} VERSAVISUAL`
  }
  return `${contextTitle} — Direção audiovisual VERSAVISUAL`
}

// ── FUNDADOR & BASTIDORES ──────────────────────────────────
export const FOUNDER_PHOTO = "/images/foto-a-producao-nao-falha.webp"

// ── ALBUMS COMPLETOS POR PRODUÇÃO ───────────────────────────
export const CLIPE_E_O_TCHAN_COVER =
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Capa-clipe-e-o-tchan-jogadinha.jpg"

export const BACKSTAGE_CLIPE_SURURU_PHOTOS: readonly string[] = [
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo1.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo2.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo3.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo4.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo5.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo6.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo7.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo8.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo9.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo10.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo11.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo12.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo13.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo14.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo15.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo16.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo17.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo18.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo19.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo20.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo21.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo22.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo23.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo24.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo25.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo26.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo27.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo28.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo29.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo30.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo31.jpg",
  "/images/Artistas & Videoclipes - Backstage Clipe Sururu/Backstage-clipe-sururu-babado-novo33.jpg",
]

export const BONFIM_HOUSE_PHOTOS: readonly string[] = [
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo1.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo2.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo3.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo4.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo5.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo6.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo7.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo8.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo9.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo10.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo11.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo12.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo13.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo14.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo15.jpg",
  "/images/Ativações & Eventos - Bonfim House/Bonfim-house-salvador-bahia-corporativo16.jpg",
]

export const CAMAROTE_ONDINA_PHOTOS: readonly string[] = [
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval1.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval2.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval3.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval4.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval5.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval6.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval7.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval8.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval9.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval10.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval11.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval12.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval13.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval14.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval15.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval16.jpg",
  "/images/Ativações & Eventos - Camarote Ondina/Camarote-Ondina-Salvador-Bahia-Carnaval17.jpg",
]

export const ENSAIO_GESTANTE_PRAIA_PHOTOS: readonly string[] = [
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral3.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral4.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral5.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral6.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral7.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral8.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral9.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral10.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral11.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral12.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral13.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral14.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral15.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral16.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral17.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral18.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral19.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral20.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral21.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral22.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral23.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral24.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral25.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral26.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral27.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral28.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral29.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral30.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral31.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral32.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral33.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral34.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral35.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral36.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral37.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral38.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral39.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral40.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral41.jpg",
]

export const ENSAIO_AUTORAL_PHOTOS: readonly string[] = [
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral1.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-Autoral2.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral42.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral43.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral44.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral45.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral46.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral47.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral48.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral49.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral50.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral51.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral52.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral53.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral54.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral55.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral56.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral57.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral58.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral59.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral60.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral61.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral62.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral63.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral64.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral65.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral66.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral67.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral68.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral69.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral70.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral71.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral72.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral73.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral74.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral75.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral76.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral77.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral78.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral79.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral80.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral81.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral82.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral83.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral84.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral85.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral86.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral87.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral88.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral89.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral90.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral91.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral92.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral93.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral94.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral95.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral96.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral97.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral98.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Autoral/Ensaio-autoral99.jpg",
]

export const ENSAIO_STREET_PHOTOS: readonly string[] = [
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street1.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street2.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street3.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street4.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street5.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street6.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street7.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street8.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street9.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street10.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street11.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street12.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street13.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street14.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street15.jpg",
  "/images/Imagem Pessoal & Lifestyle - Ensaio Street/Ensaio-street16.jpg",
]

export const FASHION_MANNERS_PHOTOS: readonly string[] = [
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners1.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners2.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners3.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners4.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners5.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners6.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners7.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners8.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners9.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners10.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners11.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners12.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners13.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners14.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners15.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners16.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners17.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners18.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners19.jpg",
  "/images/Moda & Campanhas - Fashion Manners/Fashion-Manners20.jpg",
]

export const FESTIVAL_JEANS_TORITAMA_PHOTOS: readonly string[] = [
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT1.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT2.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT3.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT4.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT5.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT6.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT7.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT8.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT9.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT10.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT11.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT12.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT13.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT14.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT15.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT16.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT17.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT18.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT19.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT20.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT21.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT22.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT23.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT24.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT25.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT26.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT27.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT28.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT29.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT30.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT31.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT32.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT33.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT34.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT35.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT36.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT37.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT38.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT39.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT40.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT41.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT42.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT43.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT45.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT46.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT47.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT48.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT49.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT50.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT51.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT52.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT53.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT54.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT56.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT57.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT59.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT60.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT61.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT63.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT64.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT66.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT68.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT71.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT72.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT73.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT74.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT75.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT76.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT77.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT78.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT79.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT80.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT81.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT82.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT83.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT84.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT85.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT86.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT87.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT88.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT89.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT90.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT91.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT92.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT96.jpg",
  "/images/Moda & Campanhas - Festival Jeans Toritama/Festival-de-Jeans-de-toritama-FJT107.jpg",
]

export const HOTELARIA_LIFESTYLE_PHOTOS: readonly string[] = [
  "/images/Hotelaria & Lifestyle/Hotelaria-life-style1.jpg",
  "/images/Hotelaria & Lifestyle/Hotelaria-life-style2.jpg",
]

export const LANCAMENTO_DRINKBALL_PHOTOS: readonly string[] = [
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay1.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay2.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay3.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay4.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay5.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay6.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay7.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay8.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay9.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay10.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay11.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay12.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay13.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay14.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay15.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay16.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay17.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay18.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay19.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay20.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay21.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay22.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay23.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay24.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay25.jpg",
  "/images/Ativações & Eventos - Lançamento Drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay35.jpg",
]

export const LOJA_FRIDA_PHOTOS: readonly string[] = [
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida1.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida2.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida3.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida4.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida5.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida6.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida7.jpg",
  "/images/Posicionamento Profissional - Loja Frida/Loja-Frida8.jpg",
]

export const MEGABLOCO_CHA_DA_ALICE_PHOTOS: readonly string[] = [
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval1.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval2.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval3.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval4.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval5.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval6.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval7.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval8.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval9.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval10.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval11.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval12.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval13.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval14.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval15.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval16.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval17.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval18.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval19.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval20.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval21.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval22.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval23.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval24.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval25.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval26.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval27.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval28.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval29.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval30.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval31.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval32.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval33.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval34.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval35.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval36.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval37.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval38.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval39.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval40.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval41.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval42.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval43.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval44.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval45.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval46.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval47.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval48.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval49.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval50.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval51.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval52.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval53.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval54.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval55.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval57.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval58.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval59.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval60.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval61.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval62.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval63.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval64.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval65.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval66.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval67.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval68.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval69.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval70.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval71.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval72.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval73.jpg",
  "/images/Ativações & Eventos - Mega Bloco Chá da Alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval82.jpg",
]

export const MODA_SANTALOLA_PHOTOS: readonly string[] = [
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola1.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola2.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola3.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola4.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola5.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola6.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola7.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola8.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola9.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola10.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola11.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola12.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola13.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola14.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola15.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola16.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola17.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola18.jpg",
  "/images/Moda & Campanhas - Santa Lolla/Moda-Santalola19.jpg",
]

export const SYN_ICE_PHOTOS: readonly string[] = [
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia1.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia2.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia3.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia4.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia5.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia6.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia7.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia8.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia9.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia10.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia11.jpg",
  "/images/Ativações & Eventos - Syn Ice/Syn-ice-Feira-super-minas-super-bahia12.jpg",
]

export const WEDDING_PHOTOS: readonly string[] = [
  "/images/Casamentos/CASAMENTO1.jpg",
  "/images/Casamentos/CASAMENTO2.jpg",
  "/images/Casamentos/CASAMENTO3.jpg",
  "/images/Casamentos/CASAMENTO4.jpg",
  "/images/Casamentos/CASAMENTO5.jpg",
  "/images/Casamentos/CASAMENTO6.jpg",
  "/images/Casamentos/CASAMENTO7.jpg",
  "/images/Casamentos/CASAMENTO8.jpg",
  "/images/Casamentos/CASAMENTO9.jpg",
  "/images/Casamentos/CASAMENTO10.jpg",
  "/images/Casamentos/CASAMENTO11.jpg",
  "/images/Casamentos/CASAMENTO12.jpg",
  "/images/Casamentos/CASAMENTO13.jpg",
  "/images/Casamentos/CASAMENTO14.jpg",
  "/images/Casamentos/CASAMENTO15.jpg",
  "/images/Casamentos/CASAMENTO16.jpg",
]

export const MATERNITY_PHOTOS: readonly string[] = ENSAIO_GESTANTE_PRAIA_PHOTOS

// ── COLEÇÕES CURADAS POR SEGMENTO ─────────────────────────────
export const PHOTOS = {
  // Ativações & Eventos
  events: [
    ...BONFIM_HOUSE_PHOTOS,
    ...CAMAROTE_ONDINA_PHOTOS,
    ...LANCAMENTO_DRINKBALL_PHOTOS,
    ...LOJA_FRIDA_PHOTOS,
    ...MEGABLOCO_CHA_DA_ALICE_PHOTOS,
    ...SYN_ICE_PHOTOS,
  ],

  // Moda & Campanhas
  fashion: [
    ...FASHION_MANNERS_PHOTOS,
    ...FESTIVAL_JEANS_TORITAMA_PHOTOS,
    ...MODA_SANTALOLA_PHOTOS,
  ],

  // Artistas & Videoclipes
  artists: [CLIPE_E_O_TCHAN_COVER, ...BACKSTAGE_CLIPE_SURURU_PHOTOS],

  // Posicionamento Profissional
  professional: ENSAIO_STREET_PHOTOS,

  // Imagem Pessoal & Lifestyle
  personal: [
    ...ENSAIO_AUTORAL_PHOTOS,
    ...ENSAIO_STREET_PHOTOS,
  ],

  // Casamentos
  weddings: WEDDING_PHOTOS,

  // Gestantes
  maternity: MATERNITY_PHOTOS,

  // Hotelaria & Lifestyle
  hotel: HOTELARIA_LIFESTYLE_PHOTOS,

  // Bastidores / BTS
  bts: [
    ...BACKSTAGE_CLIPE_SURURU_PHOTOS.slice(0, 10),
    ...FASHION_MANNERS_PHOTOS.slice(0, 8),
    ...MEGABLOCO_CHA_DA_ALICE_PHOTOS.slice(35, 45),
  ],
} as const

export const HERO_PHOTO = "/images/foto-a-producao-nao-falha.webp"
