// VERSAVISUAL Image System
// Sourced from project productions, categorized by album & segment.

const LOCAL_IMAGE_FALLBACK = "/images/megabloco-cha-da-alice/hero-poster.webp"

export function img(id: string, w = 1200, h?: number): string {
  if (!id) return ""
  if (id.startsWith("/") || id.startsWith("http") || id.startsWith("data:")) {
    return id
  }
  return LOCAL_IMAGE_FALLBACK
}

// ── ALBUMS COMPLETOS POR PRODUÇÃO ───────────────────────────
export const BACKSTAGE_CLIPE_SURURU_PHOTOS: readonly string[] = [
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo1.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo2.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo3.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo4.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo5.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo6.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo7.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo8.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo9.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo10.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo11.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo12.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo13.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo14.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo15.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo16.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo17.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo18.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo19.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo20.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo21.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo22.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo23.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo24.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo25.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo26.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo27.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo28.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo29.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo30.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo31.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo32.jpg",
  "/images/backstage-clipe-sururu/Backstage-clipe-sururu-babado-novo33.jpg",
]

export const BONFIM_HOUSE_PHOTOS: readonly string[] = [
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo1.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo2.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo3.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo4.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo5.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo6.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo7.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo8.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo9.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo10.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo11.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo12.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo13.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo14.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo15.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo16.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo28.jpg",
  "/images/bonfim-house/Bonfim-house-salvador-bahia-corporativo29.jpg",
]

export const CAMAROTE_ONDINA_PHOTOS: readonly string[] = [
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval1.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval2.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval3.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval4.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval5.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval6.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval7.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval8.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval9.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval10.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval11.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval12.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval13.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval14.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval15.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval16.jpg",
  "/images/camarote-ondina/Camarote-Ondina-Salvador-Bahia-Carnaval17.jpg",
]

export const ENSAIO_AUTORAL_PHOTOS: readonly string[] = [
  "/images/ensaio-autoral/Ensaio-Autoral1.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral2.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral3.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral4.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral5.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral6.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral7.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral8.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral9.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral10.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral11.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral12.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral13.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral14.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral15.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral16.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral17.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral18.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral19.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral20.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral21.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral22.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral23.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral24.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral25.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral26.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral27.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral28.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral29.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral30.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral31.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral32.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral33.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral34.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral35.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral36.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral37.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral38.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral39.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral40.jpg",
  "/images/ensaio-autoral/Ensaio-Autoral41.jpg",
  "/images/ensaio-autoral/Ensaio-autoral42.jpg",
  "/images/ensaio-autoral/Ensaio-autoral43.jpg",
  "/images/ensaio-autoral/Ensaio-autoral44.jpg",
  "/images/ensaio-autoral/Ensaio-autoral45.jpg",
  "/images/ensaio-autoral/Ensaio-autoral46.jpg",
  "/images/ensaio-autoral/Ensaio-autoral47.jpg",
  "/images/ensaio-autoral/Ensaio-autoral48.jpg",
  "/images/ensaio-autoral/Ensaio-autoral49.jpg",
  "/images/ensaio-autoral/Ensaio-autoral50.jpg",
  "/images/ensaio-autoral/Ensaio-autoral51.jpg",
  "/images/ensaio-autoral/Ensaio-autoral52.jpg",
  "/images/ensaio-autoral/Ensaio-autoral53.jpg",
  "/images/ensaio-autoral/Ensaio-autoral54.jpg",
  "/images/ensaio-autoral/Ensaio-autoral55.jpg",
  "/images/ensaio-autoral/Ensaio-autoral56.jpg",
  "/images/ensaio-autoral/Ensaio-autoral57.jpg",
  "/images/ensaio-autoral/Ensaio-autoral58.jpg",
  "/images/ensaio-autoral/Ensaio-autoral59.jpg",
  "/images/ensaio-autoral/Ensaio-autoral60.jpg",
  "/images/ensaio-autoral/Ensaio-autoral61.jpg",
  "/images/ensaio-autoral/Ensaio-autoral62.jpg",
  "/images/ensaio-autoral/Ensaio-autoral63.jpg",
  "/images/ensaio-autoral/Ensaio-autoral64.jpg",
  "/images/ensaio-autoral/Ensaio-autoral65.jpg",
  "/images/ensaio-autoral/Ensaio-autoral66.jpg",
  "/images/ensaio-autoral/Ensaio-autoral67.jpg",
  "/images/ensaio-autoral/Ensaio-autoral68.jpg",
  "/images/ensaio-autoral/Ensaio-autoral69.jpg",
  "/images/ensaio-autoral/Ensaio-autoral70.jpg",
  "/images/ensaio-autoral/Ensaio-autoral71.jpg",
  "/images/ensaio-autoral/Ensaio-autoral72.jpg",
  "/images/ensaio-autoral/Ensaio-autoral73.jpg",
  "/images/ensaio-autoral/Ensaio-autoral74.jpg",
  "/images/ensaio-autoral/Ensaio-autoral75.jpg",
  "/images/ensaio-autoral/Ensaio-autoral76.jpg",
  "/images/ensaio-autoral/Ensaio-autoral77.jpg",
  "/images/ensaio-autoral/Ensaio-autoral78.jpg",
  "/images/ensaio-autoral/Ensaio-autoral79.jpg",
  "/images/ensaio-autoral/Ensaio-autoral80.jpg",
  "/images/ensaio-autoral/Ensaio-autoral81.jpg",
  "/images/ensaio-autoral/Ensaio-autoral82.jpg",
  "/images/ensaio-autoral/Ensaio-autoral83.jpg",
  "/images/ensaio-autoral/Ensaio-autoral84.jpg",
  "/images/ensaio-autoral/Ensaio-autoral85.jpg",
  "/images/ensaio-autoral/Ensaio-autoral86.jpg",
  "/images/ensaio-autoral/Ensaio-autoral87.jpg",
  "/images/ensaio-autoral/Ensaio-autoral88.jpg",
  "/images/ensaio-autoral/Ensaio-autoral89.jpg",
  "/images/ensaio-autoral/Ensaio-autoral90.jpg",
  "/images/ensaio-autoral/Ensaio-autoral91.jpg",
  "/images/ensaio-autoral/Ensaio-autoral92.jpg",
  "/images/ensaio-autoral/Ensaio-autoral93.jpg",
  "/images/ensaio-autoral/Ensaio-autoral94.jpg",
  "/images/ensaio-autoral/Ensaio-autoral95.jpg",
  "/images/ensaio-autoral/Ensaio-autoral96.jpg",
  "/images/ensaio-autoral/Ensaio-autoral97.jpg",
  "/images/ensaio-autoral/Ensaio-autoral98.jpg",
  "/images/ensaio-autoral/Ensaio-autoral99.jpg",
]

export const ENSAIO_STREET_PHOTOS: readonly string[] = [
  "/images/ensaio-street/Ensaio-street1.jpg",
  "/images/ensaio-street/Ensaio-street2.jpg",
  "/images/ensaio-street/Ensaio-street3.jpg",
  "/images/ensaio-street/Ensaio-street4.jpg",
  "/images/ensaio-street/Ensaio-street5.jpg",
  "/images/ensaio-street/Ensaio-street6.jpg",
  "/images/ensaio-street/Ensaio-street7.jpg",
  "/images/ensaio-street/Ensaio-street8.jpg",
  "/images/ensaio-street/Ensaio-street9.jpg",
  "/images/ensaio-street/Ensaio-street10.jpg",
  "/images/ensaio-street/Ensaio-street11.jpg",
  "/images/ensaio-street/Ensaio-street12.jpg",
  "/images/ensaio-street/Ensaio-street13.jpg",
  "/images/ensaio-street/Ensaio-street14.jpg",
  "/images/ensaio-street/Ensaio-street15.jpg",
  "/images/ensaio-street/Ensaio-street16.jpg",
]

export const FASHION_MANNERS_PHOTOS: readonly string[] = [
  "/images/fashion-manners/Fashion-Manners1.jpg",
  "/images/fashion-manners/Fashion-Manners2.jpg",
  "/images/fashion-manners/Fashion-Manners3.jpg",
  "/images/fashion-manners/Fashion-Manners4.jpg",
  "/images/fashion-manners/Fashion-Manners5.jpg",
  "/images/fashion-manners/Fashion-Manners6.jpg",
  "/images/fashion-manners/Fashion-Manners7.jpg",
  "/images/fashion-manners/Fashion-Manners8.jpg",
  "/images/fashion-manners/Fashion-Manners9.jpg",
  "/images/fashion-manners/Fashion-Manners10.jpg",
  "/images/fashion-manners/Fashion-Manners11.jpg",
  "/images/fashion-manners/Fashion-Manners12.jpg",
  "/images/fashion-manners/Fashion-Manners13.jpg",
  "/images/fashion-manners/Fashion-Manners14.jpg",
  "/images/fashion-manners/Fashion-Manners15.jpg",
  "/images/fashion-manners/Fashion-Manners16.jpg",
  "/images/fashion-manners/Fashion-Manners17.jpg",
  "/images/fashion-manners/Fashion-Manners18.jpg",
  "/images/fashion-manners/Fashion-Manners19.jpg",
  "/images/fashion-manners/Fashion-Manners20.jpg",
]

export const FESTIVAL_JEANS_TORITAMA_PHOTOS: readonly string[] = [
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT1.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT2.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT3.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT4.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT5.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT6.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT7.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT8.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT9.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT10.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT11.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT12.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT13.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT14.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT15.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT16.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT17.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT18.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT19.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT20.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT21.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT22.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT23.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT24.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT25.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT26.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT27.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT28.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT29.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT30.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT31.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT32.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT33.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT34.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT35.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT36.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT37.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT38.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT39.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT40.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT41.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT42.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT43.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT44.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT45.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT46.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT47.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT48.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT49.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT50.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT51.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT52.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT53.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT54.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT55.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT56.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT57.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT58.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT59.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT60.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT61.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT62.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT63.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT64.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT65.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT66.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT67.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT68.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT69.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT70.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT71.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT72.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT73.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT74.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT75.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT76.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT77.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT78.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT79.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT80.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT81.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT82.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT83.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT84.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT85.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT86.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT87.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT88.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT89.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT90.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT91.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT92.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT93.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT94.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT95.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT96.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT97.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT98.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT99.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT100.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT101.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT102.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT103.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT104.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT105.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT106.jpg",
  "/images/festival-jeans-toritama/Festival-de-Jeans-de-toritama-FJT107.jpg",
]

export const HOTELARIA_LIFESTYLE_PHOTOS: readonly string[] = [
  "/images/hotelaria-lifestyle/Hotelaria-life-style1.jpg",
  "/images/hotelaria-lifestyle/Hotelaria-life-style2.jpg",
]

export const LANCAMENTO_DRINKBALL_PHOTOS: readonly string[] = [
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay1.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay2.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay3.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay4.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay5.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay6.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay7.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay8.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay9.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay10.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay11.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay12.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay13.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay14.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay15.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay16.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay17.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay18.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay19.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay20.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay21.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay22.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay23.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay24.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay25.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay26.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay27.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay28.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay29.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay30.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay31.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay32.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay33.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay34.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay35.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay36.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay37.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay38.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay39.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay40.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay41.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay42.jpg",
  "/images/lancamento-drinkball/Lanc_amentto-DrinkBall-Apas-Feira-Sa_o-Paulo-Gessika-Gkay43.jpg",
]

export const LOJA_FRIDA_PHOTOS: readonly string[] = [
  "/images/loja-frida/Loja-Frida1.jpg",
  "/images/loja-frida/Loja-Frida2.jpg",
  "/images/loja-frida/Loja-Frida3.jpg",
  "/images/loja-frida/Loja-Frida4.jpg",
  "/images/loja-frida/Loja-Frida5.jpg",
  "/images/loja-frida/Loja-Frida6.jpg",
  "/images/loja-frida/Loja-Frida7.jpg",
  "/images/loja-frida/Loja-Frida8.jpg",
]

export const MEGABLOCO_CHA_DA_ALICE_PHOTOS: readonly string[] = [
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval1.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval2.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval3.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval4.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval5.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval6.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval7.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval8.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval9.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval10.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval11.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval12.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval13.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval14.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval15.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval16.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval17.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval18.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval19.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval20.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval21.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval22.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval23.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval24.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval25.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval26.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval27.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval28.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval29.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval30.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval31.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval32.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval33.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval34.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval35.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval36.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval37.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval38.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval39.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval40.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval41.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval42.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval43.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval44.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval45.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval46.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval47.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval48.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval49.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval50.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval51.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval52.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval53.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval54.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval55.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval56.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval57.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval58.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval59.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval60.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval61.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval62.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval63.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval64.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval65.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval66.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval67.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval68.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval69.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval70.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval71.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval72.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval73.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval74.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval75.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval76.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval77.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval78.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval79.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval80.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval81.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval82.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval83.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval84.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval85.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval86.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval87.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval88.jpg",
  "/images/megabloco-cha-da-alice/Mega-Bloco-Cha-da-Alice_Rio-de-Janeiro-Babado-Novo-Mari-Antunes-Christian-Chaves-RBD-Carnaval89.jpg",
]

export const MODA_SANTALOLA_PHOTOS: readonly string[] = [
  "/images/moda-santalola/Moda-Santalola1.jpg",
  "/images/moda-santalola/Moda-Santalola2.jpg",
  "/images/moda-santalola/Moda-Santalola3.jpg",
  "/images/moda-santalola/Moda-Santalola4.jpg",
  "/images/moda-santalola/Moda-Santalola5.jpg",
  "/images/moda-santalola/Moda-Santalola6.jpg",
  "/images/moda-santalola/Moda-Santalola7.jpg",
  "/images/moda-santalola/Moda-Santalola8.jpg",
  "/images/moda-santalola/Moda-Santalola9.jpg",
  "/images/moda-santalola/Moda-Santalola10.jpg",
  "/images/moda-santalola/Moda-Santalola11.jpg",
  "/images/moda-santalola/Moda-Santalola12.jpg",
  "/images/moda-santalola/Moda-Santalola13.jpg",
  "/images/moda-santalola/Moda-Santalola14.jpg",
  "/images/moda-santalola/Moda-Santalola15.jpg",
  "/images/moda-santalola/Moda-Santalola16.jpg",
  "/images/moda-santalola/Moda-Santalola17.jpg",
  "/images/moda-santalola/Moda-Santalola18.jpg",
  "/images/moda-santalola/Moda-Santalola19.jpg",
]

export const SYN_ICE_PHOTOS: readonly string[] = [
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia1.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia2.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia3.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia4.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia5.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia6.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia7.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia8.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia9.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia10.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia11.jpg",
  "/images/syn-ice/Syn-ice-Feira-super-minas-super-bahia12.jpg",
]

export const WEDDING_PHOTOS: readonly string[] = [
  "/images/Casamentos/CASAMENTO1.jpg",
  "/images/Casamentos/CASAMENTO2.jpg",
  "/images/Casamentos/CASAMENTO3.jpg",
  "/images/Casamentos/CASAMENTO4.jpg",
  "/images/Casamentos/CASAMENTO5.jpg",
  "/images/Casamentos/CASAMENTO6.jpg",
  "/images/Casamentos/CASAMENTO7.jpg",
  "/images/Casamentos/CASAMENTO8.jpg",
  "/images/Casamentos/CASAMENTO9.jpg",
  "/images/Casamentos/CASAMENTO10.jpg",
  "/images/Casamentos/CASAMENTO11.jpg",
  "/images/Casamentos/CASAMENTO12.jpg",
  "/images/Casamentos/CASAMENTO13.jpg",
  "/images/Casamentos/CASAMENTO14.jpg",
  "/images/Casamentos/CASAMENTO15.jpg",
  "/images/Casamentos/CASAMENTO16.jpg",
]

export const MATERNITY_PHOTOS: readonly string[] = Array.from(
  { length: 39 },
  (_, index) => `/images/Gestante/Gestante${index + 1}.jpg`,
)

// ── COLEÇÕES CURADAS POR SEGMENTO ─────────────────────────────
export const PHOTOS = {
  // Ativações & Eventos
  events: [
    ...LANCAMENTO_DRINKBALL_PHOTOS.slice(0, 10),
    ...MEGABLOCO_CHA_DA_ALICE_PHOTOS.slice(0, 15),
    ...CAMAROTE_ONDINA_PHOTOS.slice(0, 8),
    ...BONFIM_HOUSE_PHOTOS.slice(0, 8),
    ...SYN_ICE_PHOTOS.slice(0, 6),
    ...FESTIVAL_JEANS_TORITAMA_PHOTOS.slice(0, 15),
  ],

  // Moda & Campanhas
  fashion: [
    ...FASHION_MANNERS_PHOTOS,
    ...MODA_SANTALOLA_PHOTOS,
    ...LOJA_FRIDA_PHOTOS,
    ...FESTIVAL_JEANS_TORITAMA_PHOTOS.slice(15, 35),
  ],

  // Artistas & Videoclipes
  artists: [...BACKSTAGE_CLIPE_SURURU_PHOTOS, ...MEGABLOCO_CHA_DA_ALICE_PHOTOS],

  // Posicionamento Profissional
  professional: [
    ...ENSAIO_AUTORAL_PHOTOS.slice(69),
    ...ENSAIO_STREET_PHOTOS,
  ],

  // Imagem Pessoal & Lifestyle
  personal: [
    ...ENSAIO_AUTORAL_PHOTOS.slice(41),
    ...ENSAIO_STREET_PHOTOS,
    ...LOJA_FRIDA_PHOTOS,
  ],

  // Casamentos
  weddings: WEDDING_PHOTOS,

  // Gestantes
  maternity: MATERNITY_PHOTOS,

  // Hotelaria & Lifestyle
  hotel: [
    ...HOTELARIA_LIFESTYLE_PHOTOS,
    ...BONFIM_HOUSE_PHOTOS.slice(0, 4),
    ...ENSAIO_AUTORAL_PHOTOS.slice(10, 14),
  ],

  // Bastidores / BTS
  bts: [
    ...BACKSTAGE_CLIPE_SURURU_PHOTOS.slice(0, 10),
    ...FASHION_MANNERS_PHOTOS.slice(0, 8),
    ...MEGABLOCO_CHA_DA_ALICE_PHOTOS.slice(35, 45),
  ],
} as const

export const HERO_PHOTO =
  "/images/megabloco-cha-da-alice/hero-poster.webp" ||
  MEGABLOCO_CHA_DA_ALICE_PHOTOS[0]
